package questions;

/**
 * Top level exception-type for this project
 * 
 * @author bshanahan
 *
 */
public class AvmException extends Exception {

	// generated by eclipse
	private static final long serialVersionUID = -6478643639422037772L;

	public AvmException(String string) {
		super(string);
	}
}
